# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/medicitas
spring.datasource.username=postgres
spring.datasource.password=ndiosa08
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=c2VjcmV0S2V5U3VwZXJTZWN1cmFQYXJhTWVkaUNpdGFzMjAyNA==
jwt.expiration=900000
jwt.refresh-expiration=604800000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html