# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/medicitas
spring.datasource.username=postgres
spring.datasource.password=ndiosa08
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=40a0a0020edee009d701d41394ccf3c143df0a0d29e7d8cbe2f770673fb31460
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html